all:user.o passenger.o driver.o vip_driver.o admin.o date_time.o galaxy.o planet.o spaceship.o address.o code.o trip.o invalid_command.o command.o server.o space_taxi_system.o main.o
	g++ user.o passenger.o driver.o vip_driver.o admin.o date_time.o galaxy.o planet.o spaceship.o address.o code.o trip.o invalid_command.o command.o server.o space_taxi_system.o main.o
	./a.out
user.o:user.cpp user.h
	g++ -c user.cpp
passenger.o:passenger.cpp passenger.h
	g++ -c passenger.cpp
driver.o:driver.cpp driver.h
	g++ -c driver.cpp
vip_driver.o:vip_driver.cpp vip_driver.h
	g++ -c vip_driver.cpp
admin.o:admin.cpp admin.h
	g++ -c admin.cpp
date_time.o:date_time.cpp date_time.h
	g++ -c date_time.cpp
galaxy.o:galaxy.cpp galaxy.h
	g++ -c galaxy.cpp
planet.o:planet.cpp planet.h
	g++ -c planet.cpp
spaceship.o:spaceship.cpp spaceship.h
	g++ -c spaceship.cpp
address.o:address.cpp address.h
	g++ -c address.cpp
code.o:code.cpp code.h
	g++ -c code.cpp
trip.o:trip.cpp trip.h
	g++ -c trip.cpp
invalid_command.o:invalid_command.cpp invalid_command.h
	g++ -c invalid_command.cpp
command.o:command.cpp command.h
	g++ -c command.cpp
server.o:server.cpp server.h
	g++ -c server.cpp 
space_taxi_system.o:space_taxi_system.cpp space_taxi_system.h
	g++ -c space_taxi_system.cpp 
main.o:main.cpp
	g++ -c main.cpp